// Populates the database from backend/prisma/seed-data.json, which is
// generated by the frontend's `npm run export:content` script (see
// h5p-interactive-app/scripts/export-content.ts). This keeps seeded content
// identical to the verified content shipped in the frontend's TS files —
// nothing here is re-typed by hand.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const prisma = new PrismaClient();

interface SeedFrame {
  id: string;
  kind: string;
  panel: string;
  title: string;
  note?: string;
  [key: string]: unknown; // kind-specific fields (body, questions, items, zones, markers, src, ...)
}

interface SeedModule {
  id: string;
  subjectId: string;
  grade: number;
  semester: number;
  title: string;
  subtitle: string;
  summary: string;
  estimatedMinutes: string;
  accent: string;
  frames: SeedFrame[];
}

interface SeedSubject {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  accent: string;
}

interface SeedData {
  subjects: SeedSubject[];
  modules: SeedModule[];
}

async function main() {
  const dataPath = path.resolve(__dirname, 'seed-data.json');
  if (!fs.existsSync(dataPath)) {
    throw new Error(
      `seed-data.json not found at ${dataPath}. Run "npm run export:content" in the frontend project first.`
    );
  }
  const seedData: SeedData = JSON.parse(fs.readFileSync(dataPath, 'utf-8'));

  console.log(`Seeding ${seedData.subjects.length} subjects...`);
  for (const subject of seedData.subjects) {
    await prisma.subject.upsert({
      where: { id: subject.id },
      create: subject,
      update: subject,
    });
  }

  console.log(`Seeding ${seedData.modules.length} modules...`);
  for (const mod of seedData.modules) {
    const { frames, ...moduleFields } = mod;

    await prisma.module.upsert({
      where: { id: mod.id },
      create: moduleFields,
      update: moduleFields,
    });

    // Replace this module's frames wholesale so removed/reordered frames in
    // the source content are reflected exactly (rather than merging stale rows).
    await prisma.frame.deleteMany({ where: { moduleId: mod.id } });

    await prisma.frame.createMany({
      data: frames.map((frame, index) => {
        const { id, kind, panel, title, note, ...rest } = frame;
        return {
          moduleId: mod.id,
          slug: id,
          kind,
          panel,
          title,
          note: note ?? null,
          order: index,
          data: rest, // everything else (body, questions, items, zones, markers, src, instructions, ...)
        };
      }),
    });
  }

  const moduleCount = await prisma.module.count();
  const frameCount = await prisma.frame.count();
  console.log(`Done. Database now has ${moduleCount} modules and ${frameCount} frames.`);

  console.log('Seeding subscription plans...');
  const plans = [
    {
      id: 'free_trial',
      name: 'Free Trial',
      priceIdr: 0,
      interval: 'trial',
      trialDays: 14,
      features: ['Semua fitur', 'Berlaku 14 hari', 'Tanpa kartu kredit'],
    },
    {
      id: 'basic',
      name: 'Basic',
      priceIdr: 150000,
      interval: 'month',
      trialDays: null,
      features: ['Fitur utama', 'Akses semua modul kelas 1-6', 'Progres & riwayat belajar'],
    },
    {
      id: 'pro',
      name: 'Pro',
      priceIdr: 500000,
      interval: 'month',
      trialDays: null,
      features: ['Semua fitur Basic', 'Analytics & laporan lanjutan', 'Dukungan prioritas'],
    },
  ];
  for (const plan of plans) {
    await prisma.plan.upsert({ where: { id: plan.id }, create: plan, update: plan });
  }

  console.log('Seeding demo accounts...');
  const demoAccounts = [
    { name: 'Bu Guru Demo', email: 'guru@sekolah.id', password: 'guru12345', role: 'TEACHER' as const, planId: 'pro' },
    { name: 'Murid Demo', email: 'murid@sekolah.id', password: 'murid12345', role: 'STUDENT' as const, planId: 'free_trial' },
  ];
  for (const acc of demoAccounts) {
    const passwordHash = await bcrypt.hash(acc.password, 10);
    const user = await prisma.user.upsert({
      where: { email: acc.email },
      create: { name: acc.name, email: acc.email, passwordHash, role: acc.role },
      update: {},
    });
    const periodDays = acc.planId === 'free_trial' ? 14 : 30;
    await prisma.subscription.upsert({
      where: { userId: user.id },
      create: {
        userId: user.id,
        planId: acc.planId,
        status: acc.planId === 'free_trial' ? 'TRIALING' : 'ACTIVE',
        currentPeriodEnd: new Date(Date.now() + periodDays * 24 * 60 * 60 * 1000),
      },
      update: {},
    });
  }
  console.log(
    `Demo accounts ready:\n  Guru (Pro): guru@sekolah.id / guru12345\n  Murid (Free Trial): murid@sekolah.id / murid12345\n  (Ganti/hapus di production!)`
  );
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
